---
- name: Deploy web application
  hosts: all
  tasks:
    - name: Install OS packages
      apt: 
        name: "{{ item }}"
        state: latest
      with_items: 
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-flask
        - python3-psycopg2
        - libpq-dev

    - name: Disalbe this for container
      shell: python3 -m pip config set global.break-system-packages true
    - ansible.builtin.include_tasks: tasks/install_flask.yml 
    - ansible.builtin.include_tasks: tasks/copy_files.yml
    - ansible.builtin.include_tasks: tasks/init_db.yml
    - ansible.builtin.include_tasks: tasks/start_app.yml