---
- name: Deploy web application
  hosts: all
  tasks:
    - name: Install OS packages
      apt: 
        name: "{{ item }}"
        state: latest
      with_items: 
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-flask
        - python3-psycopg2
        - libpq-dev

    - name: Disalbe this for container
      shell: python3 -m pip config set global.break-system-packages true

    - name: Install python flask package
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      with_items:
        - Flask
        - psycopg2-binary

    - name: Copy py files to remote
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /root/flask_app/
      with_items: 
        - init_db.py
        - app.py

    - name: Copy html files to remote
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /root/flask_app/templates/
      with_items: 
        - index.html
        - create.html
        - base.html

    - name: execute initiate/delete old rows in DB
      ansible.builtin.shell: |
        cd /root/flask_app/
        python3 init_db.py
    
    - name: Start the App
      ansible.builtin.shell: |
            cd /root/flask_app/
            export FLASK_APP=app
            export FLASK_ENV=development
            nohup flask run --host=0.0.0.0 &