#https://stackoverflow.com/questions/46032392/docker-compose-does-not-allow-to-use-local-images
version: '3'
services:
  node1:
    image: ansible-new:latest
    tty: true
    volumes:
      - /Users/suresh/Documents/GitHub/ansible/mybooks:/app
      # - /Users/suresh/.ansible:/etc/ansible
    ports:
      - 1111:22
  
  node2:
    image: ansible-new:latest
    tty: true
    volumes:
      - /Users/suresh/Documents/GitHub/ansible/mybooks:/app
      # - /Users/suresh/.ansible:/etc/ansible
    ports:
      - 2222:22